### ISSUE TITLE
keyerror update_time

### ISSUE THREAD

**Issue by Juliepvr** [galaxyproject/galaxy-upload#12]
Hi, I have been trying multiple ways to use galaxy-upload, but I always get the same error message:

Traceback (most recent call last):
  File "/group/yield/Users/jupev/.conda/envs/galaxy2/bin/galaxy-history-search", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/group/yield/Users/jupev/.conda/envs/galaxy2/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/group/yield/Users/jupev/.conda/envs/galaxy2/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/group/yield/Users/jupev/.conda/envs/galaxy2/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/group/yield/Users/jupev/.conda/envs/galaxy2/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/group/yield/Users/jupev/.conda/envs/galaxy2/lib/python3.11/site-packages/galaxy_upload/history.py", line 84, in main
    table = make_table(quiet, histories=histories)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/group/yield/Users/jupev/.conda/envs/galaxy2/lib/python3.11/site-packages/galaxy_upload/history.py", line 30, in make_table
    history["update_time"]
    ~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'update_time'

I have tried with docker, a local installation in the base environment and an anaconda environment, both from my personal computer and via my works linux server. It is always the same error message **KeyError: 'update_time'** 
Does anybody have an idea what is going wrong?

Kind regards,
Julie

**Comment by bgruening** [comment]
@Juliepvr against which Galaxy server or version are you trying this?

**Comment by Juliepvr** [comment]
Hi, I just found out usegalaxy.be is an older version (21.01) , when using galaxy-upload with usegalaxy.eu I don't encounter any problems. Thanks!

**Comment by bgruening** [comment]
Thanks @Juliepvr for letting us know.
